spring:
  application:
    name: api-gateway

server:
  port: 4444

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

#  single-instance
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-consumer

    api-b:
      path: /api-b/**
      serviceId: eureka-client
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000


#  multi-instance
#    api-b:
#      path: /api-b/**
#      serviceId: api-b

#api-b:
#  ribbon:
#    listOfServers: http://localhost:3333/, http://localhost:3334/


#添加ribbon的超时时间设置
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000


hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeout-in-milliseconds: 3000